# -*- coding: utf-8 -*-
"""few-shot_instruction_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBYnej587yYWwynAJUpxKj5FwOIAcSRw
"""


import openai

OPENAI_API_KEY= ''

def generate_instruction(prompt,caption):

  system_message = {
        "role": "system",
        "content": (
            "determine the task, object for the task, and the grasping location on the object based on the input prompt and the input image caption.\n\n"
            "###EXAMPLE###\n\n"
            "input prompt: Fetch the bottle\n"
            "input image caption: image of a bottle\n"
            "task: pick up and bring the bottle to the user\n"
            "object: bottle\n"
            "grasping location: bottle's body\n"
            "\\\\\\\n"
            "input prompt: Im thirsty\n"
            "input image caption: image of a bottle\n"
            "task: pick up and bring the water bottle to the user\n"
            "object: bottle\n"
            "grasping location: bottle's body\n"
            "\\\\\\\n"
            "input prompt: i want to brush my teeth\n"
            "input image caption: image of a toothbrush\n"
            "task: pick up and bring the toothbrush to the user\n"
            "object: toothbrush\n"
            "grasping location: toothbrush's head\n"
            "\\\\\\\n"
            "input prompt: i want coffee\n"
            "input image caption: image of a cup\n"
            "task: pick up and bring the coffee cup to the user\n"
            "object: cup\n"
            "grasping location: cup's handle\n"
            "\\\\\\\n"
            "input prompt: Move the vase\n"
            "input image caption: image of a vase\n"
            "task: Reposition the vase to a new location\n"
            "object: vase\n"
            "grasping location: vase's body\n"
            "\\\\\\\n"
            "input prompt: change the channel\n"
            "input image caption: image of a remote\n"
            "task: pick up the remote\n"
            "object: remote\n"
            "grasping location: remote's body\n"
            "\\\\\\\n"
            "input prompt: i want wine\n"
            "input image caption: image of a wine glass\n"
            "task: pick up and bring the wine glass to the user\n"
            "object: wine glass\n"
            "grasping location: wine glass's stem\n"
            "\\\\\\\n"
            "input prompt: i want soupe\n"
            "input image caption: image of a bowl\n"
            "task: pick up and bring the soupe bowl to the user\n"
            "object: bowl\n"
            "grasping location: bowl's edge\n"
            "\\\\\\\n"
            "input prompt: flip the bottle\n"
            "input image caption: image of a bottle\n"
            "task: pick up and flip the bottle\n"
            "object: bottle\n"
            "grasping location: bottle's neck"
            "\\\\\\\n"

        )
  }
  user_message_promot = {
      "role": "user",
      "content": f"input promopt: {prompt}"
  }
  user_message_caption = {
      "role": "user",
      "content": f"input image caption: {caption}"
  }

  messages = [system_message, user_message_promot,user_message_caption]


  try:
    client = openai.OpenAI(
        api_key = OPENAI_API_KEY
    )
    response =  client.chat.completions.create(
          model="gpt-3.5-turbo",
          messages=messages,
          temperature=1,
          max_tokens=256,
          top_p=1,
          frequency_penalty=0,
          presence_penalty=0
      )
    return response.choices[0].message.content

  except Exception as e:
    print(e)



