# -*- coding: utf-8 -*-
"""fine_tuned_Blip_Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15prlKkCAHTQ2O-tMmPiUSsw_-U5qUqGa
"""


from transformers import AutoProcessor, BlipForConditionalGeneration
from PIL import Image
import torch

processor = AutoProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
fine_tuned_model = BlipForConditionalGeneration.from_pretrained("/content/drive/MyDrive/LLM final project/fine-tuned model" ,torch_dtype=torch.float16).to("cuda")
base_model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large" ,torch_dtype=torch.float16).to("cuda")
device = "cuda" if torch.cuda.is_available() else "cpu"

def generate_caption(image,model):
  text = "grasping location: "
  inputs = processor(images=image,text=text, return_tensors="pt").to(device, torch.float16)
  pixel_values = inputs.pixel_values

  generated_ids = model.generate(pixel_values=pixel_values, max_length=25)
  generated_caption = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
  return generated_caption